package com.myteam.dfjsgjkg;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class mnvbjkxbvj implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public mnvbjkxbvj() {
    }




}